In [1]:
a=1
print(a)

1


In [2]:
a=int(input("enter first number"));
b=int(input("Enter second number"));
sum=a+b
print(sum)


enter first number7
Enter second number8
15


In [3]:
def mark(self,sum,avg):
    a=int(input("Enter a "))

In [4]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:

r=np.arange(0,10,2)
r




array([0, 2, 4, 6, 8])

In [7]:
b=np.array([4,5,6])
a+b


array([5, 7, 9])

In [8]:
a-b

array([-3, -3, -3])

In [9]:
np.mean(a)

2.0

In [10]:
np.max(a)

3

In [11]:
c=np.array([[1,2],[3,4]])

In [12]:
c

array([[1, 2],
       [3, 4]])

In [12]:
c=np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [13]:
c+d

NameError: name 'd' is not defined

In [ ]:
c+d

In [ ]:
c*d

In [ ]:
f=np.dot(c,d)
f

In [ ]:
e=c*d
e

In [ ]:
f.T

In [ ]:
print("\n matrix 1:\n",c)
print("\n matrix 1:\n",c)
print("\n addition:\n",c+d)
print("\n subtraction:\n",c-d)
print("\n multplication(Element wise):\n",c*d)
print("\n dot multiplication (row * coloumn):\n",f)
print("\n Transpose:\n",f.T)