In [1]:
a=1
print(a)

1


In [2]:
a=int(input("enter first number"));
b=int(input("Enter second number"));
sum=a+b
print(sum)


enter first number5
Enter second number5
10


In [3]:
def mark(self,sum,avg):
    a=int(input("Enter a "))

In [4]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:

r=np.arange(0,10,2)
r




array([0, 2, 4, 6, 8])

In [7]:
b=np.array([4,5,6])
a+b


array([5, 7, 9])

In [8]:
a-b

array([-3, -3, -3])

In [9]:
np.mean(a)

2.0

In [10]:
np.max(a)

3

In [11]:
c=np.array([[1,2],[3,4]])

In [12]:
c

array([[1, 2],
       [3, 4]])

In [13]:
d=np.array([[1,4],[8,4]])

In [14]:
c+d

array([[ 2,  6],
       [11,  8]])

In [15]:
c+d

array([[ 2,  6],
       [11,  8]])

In [16]:
c*d

array([[ 1,  8],
       [24, 16]])

In [17]:
f=np.dot(c,d)
f

array([[17, 12],
       [35, 28]])

In [18]:
e=c*d
e

array([[ 1,  8],
       [24, 16]])

In [19]:
f.T

array([[17, 35],
       [12, 28]])

In [20]:
print("\n matrix 1:\n",c)
print("\n matrix 1:\n",c)
print("\n addition:\n",c+d)
print("\n subtraction:\n",c-d)
print("\n multplication(Element wise):\n",c*d)
print("\n dot multiplication (row * coloumn):\n",f)
print("\n Transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 1:
 [[1 2]
 [3 4]]

 addition:
 [[ 2  6]
 [11  8]]

 subtraction:
 [[ 0 -2]
 [-5  0]]

 multplication(Element wise):
 [[ 1  8]
 [24 16]]

 dot multiplication (row * coloumn):
 [[17 12]
 [35 28]]

 Transpose:
 [[17 35]
 [12 28]]
