In [1]:
a=1
print(a)

1


In [ ]:
a=int(input("enter first number"));
b=int(input("Enter second number"));
sum=a+b
print(sum)


In [ ]:
def mark(self,sum,avg):
    a=int(input("Enter a "))

In [1]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:

r=np.arange(0,10,2)
r




array([0, 2, 4, 6, 8])

In [4]:
b=np.array([4,5,6])
a+b


array([5, 7, 9])

In [5]:
a-b

array([-3, -3, -3])

In [6]:
np.mean(a)

2.0

In [7]:
np.max(a)

3

In [8]:
c=np.array([[1,2],[3,4]])

In [17]:
c

array([[1, 2],
       [3, 4]])

In [10]:
c+d

NameError: name 'd' is not defined

In [16]:
d=np.array([[4,8],[18,36]])
d

array([[ 4,  8],
       [18, 36]])

In [12]:
c+d

array([[ 5, 10],
       [21, 40]])

In [13]:
c*d

array([[  4,  16],
       [ 54, 144]])

In [15]:
f=np.dot(c,d)
f

array([[ 40,  80],
       [ 84, 168]])

In [18]:
e=c*d
e

array([[  4,  16],
       [ 54, 144]])

In [19]:
f.T

array([[ 40,  84],
       [ 80, 168]])

In [20]:
print("\n matrix 1:\n",c)
print("\n matrix 1:\n",c)
print("\n addition:\n",c+d)
print("\n subtraction:\n",c-d)
print("\n multplication(Element wise):\n",c*d)
print("\n dot multiplication (row * coloumn):\n",f)
print("\n Transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 1:
 [[1 2]
 [3 4]]

 addition:
 [[ 5 10]
 [21 40]]

 subtraction:
 [[ -3  -6]
 [-15 -32]]

 multplication(Element wise):
 [[  4  16]
 [ 54 144]]

 dot multiplication (row * coloumn):
 [[ 40  80]
 [ 84 168]]

 Transpose:
 [[ 40  84]
 [ 80 168]]
