In [4]:
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [5]:
iris=datasets.load_iris()

In [6]:
X=iris.data

In [7]:
y=iris.target

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
nb_classifier=GaussianNB()

In [10]:
nb_classifier.fit(X_train,y_train)

GaussianNB()

In [11]:
y_pred=nb_classifier.predict(X_test)

In [12]:
accuracy=accuracy_score(y_test,y_pred)

In [13]:
print(accuracy)

1.0


In [14]:
print(f"Accuracy:{accuracy*100:.2f}%")

Accuracy:100.00%


# code2

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [16]:
iris=datasets.load_iris()
X=iris.data
y=iris.target
#split the data into training and testing sets(80% training,20% testing)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
nb_classifier=GaussianNB()

In [18]:
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)

In [19]:
res=confusion_matrix(y_test,y_pred)
print("confusion_matrix \n",res)


confusion_matrix 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [20]:
res1=classification_report(y_test,y_pred)
print("Classification_report \n",res1)

Classification_report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [22]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:\n",accuracy*100)

Accuracy:
 100.0


# reference

In [23]:
import numpy as np 
import pandas as pd
# from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [25]:
data = pd.read_csv('food.csv')
X = data.iloc[:, :3]
# print(X)
y= data.iloc[:, 3]
le = LabelEncoder()


In [28]:
categorical_columns = ['Ingredient'] 
for col in categorical_columns:
 X [col] = le.fit_transform(X[col])
y = le.fit_transform(y)

In [34]:
y

array([0, 1, 0, 2, 2, 1, 2, 1, 0, 2, 2, 1, 0, 0, 1])

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
jubin = GaussianNB()
jubin.fit(X_train,y_train)
y_pred = knn.predict(X_test)


In [43]:
sample=[[1,10,9]]
k=jubin.predict(sample)

In [44]:
print(k)

[0]


In [45]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

1.0


In [46]:
le.inverse_transform([k])[0]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


'fruit'